---
title: "slab_alice_unreal"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(gazer)
library(ggpubr)
library(lubridate)
library(ggpubr)
library(viridis)
```

```{r}
fix.time <- function(df){
  
  library(lubridate)
  library(stringi)
  
  print("Adding column of full datetime ..")
  gc()
  times <- as.character(df$TimeStamp)
  x <- c(":",":",".")
  y <- c(2,4,6)
  changes <- data.frame( x, y)
  
  for(ii in seq(1,length(times))){
    extra <- 0
    
    for(jj in seq(1,dim(changes)[1])){
      
      stri_sub(times[ii],changes[jj,2]+1+extra,changes[jj,2]+extra) <- changes[jj,1]
      extra = extra+1
    }
  }
  gc()
  
  df$time_full <- as.POSIXct(times, "%H:%M:%OS",tz="Israel")
  print("Adding column of milliseconds ..")
  
  secs <- second(df$time_full)
  counter = 0
  start_time = secs[1]*1000
  
  temp=vector()
  temp[1]=start_time
  
  for(i in seq(from=2,to=length(secs))){
    if(secs[i]<1 && secs[i-1]>59){
      counter=counter+1
    }
    temp[i] <-  (secs[i] + 60*counter)*1000
  }
  
  df$time <- temp-temp[1]
  return(df)
  }

add.visibility <- function(df){
  
  print("Adding markers for what the participant was viewing ...")
  
  visibility <- vector()
  curr_visible <- "Darkness"
  visibility[1]<- curr_visible
  
  for(i in seq(2,length(df$FrameNumber))){
    if(as.character(df$SecondarySceneName[i]) == "Log: BlockViewDropOrder"){
      curr_visible <- df$SceneName[i]
    }
    if(as.character(df$SecondarySceneName[i]) == "Log: BlockViewTurnOnOrder"){
      curr_visible <- "Darkness"
    }
    visibility[i] <- curr_visible
  }
  df$What.Visible <- visibility
  return(df)
}

add.baseline.message <- function(df){

  df %>% 
    group_by(trial) %>% 
    mutate(message = ifelse(time == max(time),"target",NA)) -> df
  
  return(df)
}

condition.fix <- function(x){
  
  code <- c(6001,6002,1201,1202,29,33,3001,3002,2201,2202)
  alterations <- c("Shrink","Grow","SlowTime","FastTime","RealDelay","Ripple","HighSaturation","LowSaturation","LowGravity","HighGravity")
  
  pos <- which(x == code)
  alteration <- alterations[pos]
  return(alteration)
}
```

```{r}
path.to.data <- choose.dir(default = "", caption = "Select folder")

df <- file.path(path.to.data,"TrackersOutputData.csv") %>% read.csv()

df.trials <- file.path(path.to.data,"trials.csv") %>% read.csv() %>% select(X1.1,X0.12,X1) %>% rename(trial = X1.1, Alteration = X0.12, Magnitude = X1) 
df.trials$Alteration <- unlist(lapply(df.trials$Alteration, condition.fix)) # convert codes of alterations into titles

df.answers <- file.path(path.to.data,"Answers.csv") %>% read.csv() %>% select(BlockNumber,QuestionResult) %>% rename(trial = BlockNumber) %>% filter (trial!=1)
```

```{r}
df %>% add.visibility() -> df # add a column that specifies what the subject was looking at (Darkness, Room, Question)
df %>% mutate(FrameNumber = as.factor(FrameNumber))  %>% group_by(FrameNumber)  %>% filter (!duplicated(FrameNumber)) -> df # remove duplicate columns
df %>% rename(trial = BlockNumber) %>% filter(trial!=1) -> df #clean trials and remove callibration phase
df %>% fix.time() %>% group_by(trial) %>% mutate(time = time - first(time)) -> df # add a column that for each trial restarts the time in milliseconds
df %>% add.baseline.message() -> df # adds a message column where the target message is used in the baseline removal
df$subject <- rep(1,length(df$FrameNumber))
ifelse(df$right.pupil_diameter_mm == -1,NA,df$right.pupil_diameter_mm) -> df$right.pupil_diameter_mm
ifelse(df$left.pupil_diameter_mm  == -1,NA,df$left.pupil_diameter_mm) ->  df$left.pupil_diameter_mm
```

```{r}
df %>% 
  right_join(.,df.trials,by="trial")  %>% # add alteration and magnitude from trials.csv
  right_join(.,df.answers,by="trial")  %>% # add subject response from Answers.csv
  select(subject,time,trial,message,
              right.pupil_diameter_mm,left.pupil_diameter_mm,
              right.gaze_direction_normalized.x,right.gaze_direction_normalized.y,right.gaze_direction_normalized.z,
              left.gaze_direction_normalized.x,left.gaze_direction_normalized.y,left.gaze_direction_normalized.z,
              LastObject,What.Visible,Alteration,Magnitude,QuestionResult) -> df.eye.raw

 df.eye.raw$Alteration <- as.factor(df.eye.raw$Alteration)
 df.eye.raw$What.Visible <- as.factor(df.eye.raw$What.Visible)
  df.eye.raw$Magnitude <- as.factor(df.eye.raw$Magnitude)
```


```{r,fig.height = 6, fig.width = 15}
corr <- ggplot(data=df.eye.raw,aes(x=right.pupil_diameter_mm,left.pupil_diameter_mm))+
  geom_point()+
  ggtitle(sprintf("Right/Left Diameter - Correlation: %.3f",cor(df$right.pupil_diameter_mm,df$left.pupil_diameter_mm,use="complete.obs")))+
  labs(x="Right",y="Left")+ 
  theme(plot.title = element_text(size = 10))

x <- ggplot(data=df.eye.raw,aes(x=right.gaze_direction_normalized.x,left.gaze_direction_normalized.x))+
  geom_point()+
  ggtitle(sprintf("Right/Left X position - Correlation: %.3f",cor(df$right.gaze_direction_normalized.x, df$left.gaze_direction_normalized.x)))+
  labs(x="Right",y="Left")+ 
  theme(plot.title = element_text(size = 10))

y <- ggplot(data=df.eye.raw,aes(x=right.gaze_direction_normalized.y,left.gaze_direction_normalized.y))+
  geom_point()+
  ggtitle(sprintf("Right/Left Y position - Correlation: %.3f",cor(df$right.gaze_direction_normalized.y, df$left.gaze_direction_normalized.y)))+
  labs(x="Right",y="Left")+ 
  theme(plot.title = element_text(size = 10))

z <- ggplot(data=df.eye.raw,aes(x=right.gaze_direction_normalized.z,left.gaze_direction_normalized.z))+
  geom_point()+
  ggtitle(sprintf("Right/Left Z position - Correlation: %.3f",cor(df$right.gaze_direction_normalized.z, df$left.gaze_direction_normalized.z)))+
  labs(x="Right",y="Left")+ 
  theme(plot.title = element_text(size = 10))

ggarrange(corr,x,y,z,ncol=2,nrow=2)
```

```{r,fig.height = 6, fig.width = 15}
trials <- 2

raw<-ggplot(data=df.eye.raw[df.eye.raw$trial %in% trials,],aes(x=time,y=right.pupil_diameter_mm))+
  geom_path()

raw
```
```{r,fig.height = 6, fig.width = 15}
df.eye.pup_extended<- df.eye.raw %>% 
  mutate(extendpupil=extend_blinks(right.pupil_diameter_mm, fillback=100, fillforward=100, hz=90))


extended<-ggplot(data=df.eye.pup_extended[df.eye.pup_extended$trial %in% trials,],aes(x=time,y=extendpupil))+
  geom_path()+
  facet_wrap(~trial)

ggarrange(raw,extended,nrow=2)
```



```{r,fig.height = 6, fig.width = 15}

df.eye.smooth_interp <- smooth_interpolate_pupil(df.eye.pup_extended, 
                                          pupil="right.pupil_diameter_mm", 
                                          extendpupil="extendpupil", 
                                          extendblinks=TRUE, 
                                          step.first="interp", 
                                          filter="moving",
                                          maxgap=Inf, 
                                          type="linear", 
                                          hz=90, 
                                          n=5)

smoothed <-ggplot(data=df.eye.smooth_interp[df.eye.smooth_interp$trial %in% trials,],aes(x=time,y=pup_interp))+
  geom_path()+
  facet_wrap(~trial)

ggarrange(raw,extended,smoothed,nrow=3)
```


```{r fig1, fig.height = 6, fig.width = 15}
df.eye.baseline <- baseline_correction_pupil_msg(datafile = df.eye.smooth_interp,
                                                 pupil_colname = "pup_interp",
                                                 baseline_dur = 10,
                                                 event="target")

baselined <-ggplot(data=df.eye.baseline[df.eye.baseline$trial %in% trials,],aes(x=time,y=baselinecorrectedp))+
  geom_path()+
  facet_wrap(~trial)

ggarrange(raw,extended,smoothed,baselined,nrow=4)
```


```{r}
before<-ggplot(df.eye.baseline,aes(x=baselinecorrectedp))+
  geom_histogram(aes(y=..count..),color="red",binwidth=.005)+
  ggtitle("Pupil Values before outlier removal ")

df.eye.outliers <- df.eye.baseline %>%
  filter(baselinecorrectedp>=-2 & baselinecorrectedp<=2)

after <- ggplot(df.eye.outliers,aes(x=baselinecorrectedp))+
  geom_histogram(aes(y=..count..),color="red",binwidth=.005)+
  ggtitle("Pupil Values after outlier removal ")

ggarrange(before,after,ncol=2)
```

```{r,fig2, fig.height = 15, fig.width = 17}
df.eye.pupilz<-df.eye.outliers%>% 
  group_by(subject, trial) %>% 
  mutate(pupilz=scale(baselinecorrectedp))


pupilz <-ggplot(data=df.eye.pupilz[df.eye.pupilz$trial %in% trials,],aes(x=time,y=pupilz))+
  geom_path()+
  facet_wrap(~trial)

ggarrange(raw,extended,smoothed,baselined,pupilz,nrow=5)
```


```{r,fig5,fig.height = 7, fig.width = 17}
r.eye <- ggplot(data=df.eye.pupilz,aes(x=right.gaze_direction_normalized.x,y=right.gaze_direction_normalized.y,color=pupilz))+
  geom_point()+
  scale_color_viridis(option = "D")
l.eye <- ggplot(data=df.eye.pupilz,aes(x=left.gaze_direction_normalized.x,y=left.gaze_direction_normalized.y,color=pupilz))+
  geom_point()+
  scale_color_viridis(option = "D")

ggarrange(r.eye,l.eye,ncol = 2)
```
```{r}
df.eye.pupilz %>%
  filter(What.Visible=="Room") ->df.eye.forPlots


ggplot(df.eye.pupilz,aes(x=time,y=pupilz))+
  geom_smooth()+
  ggtitle("품vg. Pupil")+
  labs(x="Time(ms)",y="Norm. Pupil")
```
```{r,fig.height = 10, fig.width = 14}

ggplot(df.eye.forPlots,aes(x=time,y=pupilz))+
  geom_smooth()+
  ggtitle("품vg. Pupil")+
  labs(x="Time(ms)",y="Norm. Pupil")+
  facet_wrap(~Alteration)+
  ggtitle("Overall Average of Pupil Timecourse per. Alteration")
```
```{r,fig.width = 14}
ggplot(df.eye.forPlots,aes(x=time,y=pupilz,color=Magnitude))+
  geom_smooth()+
  ggtitle("품vg. Pupil per Magnitude")+
  labs(x="Time(ms)",y="Norm. Pupil")
```

```{r,fig.width = 15,fig.height = 12}
ggplot(df.eye.forPlots,aes(x=time,y=pupilz,color=Magnitude))+
  geom_smooth()+
  ggtitle("품vg. Pupil")+
  labs(x="Time(ms)",y="Norm. Pupil")+
  facet_wrap(~Alteration)+
  ggtitle("Overall Average of Pupil Timecourse per. Alteration")
```
```{r}
df.eye.forPlots %>%
  group_by(Alteration,Magnitude)%>%
  summarise(pupil = mean(pupilz)) -> pupil_summary

pup_magn <- ggline(pupil_summary,x="Magnitude", y="pupil",add = c("mean_se"),title ="Mean pupil size per Magnitude",xlab = "Magnitude",ylab = "Normalized Pupil Size")
pup_magn
```
```{r,fig.width = 15}
ggplot(data=pupil_summary, aes(x=Magnitude, y=pupil)) +
  stat_summary(fun = mean, geom="point") +
  stat_summary(fun=mean, geom="line",group = 1) + 
  facet_wrap(~Alteration)+
  ggtitle("Pupil Size ~ Magnitude x Alteration")
```
